### ISSUE TITLE
ARCOMMANDS_Generator_GenerateARDrone3SpeedSettingsOutdoor does not work. 

### ISSUE THREAD

**Issue by webventil** [ARDroneSDK3/libARCommands#8]
I am trying to set the speedSettings to outdoor. Before that I disable hull protection by calling ``ARCOMMANDS_Generator_GenerateARDrone3SpeedSettingsHullProtection``. After setting the Hull Protection, the callback is being called. For setting the outdoor speed setting, the callback is not being called. Therefore I assume, that that function does not work.
```
- (BOOL)setSpeedSettingsOutdoor
{
   u_int8_t cmdBuffer[128];
   int32_t cmdSize = 0;
   eARCOMMANDS_GENERATOR_ERROR cmdError;
   eARNETWORK_ERROR netError = ARNETWORK_ERROR;

   cmdError = ARCOMMANDS_Generator_GenerateARDrone3SpeedSettingsOutdoor(cmdBuffer, sizeof(cmdBuffer), &cmdSize, 1);
   if (cmdError == ARCOMMANDS_GENERATOR_OK)
   {
      netError = ARNETWORK_Manager_SendData(_netManager, BD_NET_C2D_NONACK, cmdBuffer, cmdSize, NULL, &(arnetworkCmdCallback), 1);
   }
   
   if ((cmdError != ARCOMMANDS_GENERATOR_OK) || (netError != ARNETWORK_OK))
   {
      return NO;
   }
   
   return YES;
}
```

**Comment by djavan-bertrand** [comment]
Hi, 

On which version of the Bebop are you testing ? This speed setting outdoor is not taken in consideration by the Bebop anymore on recent versions. We will mention it soon in the comments of commands.

What did you want to achieve by using this command ? I can maybe show you another command that makes what you want.

Best regards, 
Djavan

**Comment by webventil** [comment]
Hi,

I am using 1.98.10. So if you say, this is not supported anymore, I now should set the speed settings (altitude, rotation, tilt, etc.) manually? Thats also ok for me. I just want to the drone outside and try to pimp the fly parameters a little bit. In addition to that, the function should return an error when calling and there should be a hint in the documentation.

Thank you!

**Comment by djavan-bertrand** [comment]
In your version, the drone is always in outdoor mode (it will always try to acquire a gps fix and other outdoor stuffs).
To pimp the fly params, you can use specify the max vertical speed and max rotation speed.

Thanks for your feedback, it will be taken in consideration.

Regards, 
Djavan
